### ISSUE TITLE
kvm install stuck

### ISSUE THREAD

**Issue by 13567436138** [kinvolk/Flatcar#1679]
![Image](https://github.com/user-attachments/assets/295019ae-ad31-4ba4-bf1e-b68b60156c69)

yaml
```
variant: flatcar
version: 1.0.0
passwd:
  users:
  - name: core
    ssh_authorized_keys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHOVQ1pd6S2hslK+FycdrpWmsPYNQoGsjjccaEWH2478 root@mark-VMware-Virtual-Platform

storage:
  files:
    - path: /etc/hostname
      contents:
        inline: k8s-master01
    - path: /etc/systemd/network/10-eth0.network
      contents:
        inline: |
          [Match]
          Name=eth0

          [Network]
          Address=192.168.229.170/24
          Gateway=192.168.229.2
          DNS=8.8.8.8 
    - path: /opt/bin/kubectl
      mode: 0755
      contents:
        source: https://dl.k8s.io/v1.31.0/bin/linux/amd64/kubectl
    - path: /opt/bin/kubeadm
      mode: 0755
      contents:
        source: https://dl.k8s.io/v1.31.0/bin/linux/amd64/kubeadm
    - path: /opt/bin/kubelet
      mode: 0755
      contents:
        source: https://dl.k8s.io/v1.31.0/bin/linux/amd64/kubelet
    - path: /etc/systemd/system/kubelet.service
      contents:
        source: https://raw.githubusercontent.com/kubernetes/release/v0.14.0/cmd/kubepkg/templates/latest/deb/kubelet/lib/systemd/system/kubelet.service
    - path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
      contents:
        source: https://raw.githubusercontent.com/kubernetes/release/v0.14.0/cmd/kubepkg/templates/latest/deb/kubeadm/10-kubeadm.conf
    - path: /etc/kubeadm.yml
      contents:
        inline: |
            apiVersion: kubeadm.k8s.io/v1beta4
            bootstrapTokens:
            - groups:
              - system:bootstrappers:kubeadm:default-node-token
              token: abcdef.0123456789abcdef
              ttl: 24h0m0s
              usages:
              - signing
              - authentication
            kind: InitConfiguration
            localAPIEndpoint:
              advertiseAddress: 192.168.229.170
              bindPort: 6443
            nodeRegistration:
              criSocket: unix:///var/run/containerd/containerd.sock
              imagePullPolicy: IfNotPresent
              name: k8s-master01
              taints: null
            ---
            apiServer:
              timeoutForControlPlane: 4m0s
            apiVersion: kubeadm.k8s.io/v1beta4
            certificatesDir: /etc/kubernetes/pki
            clusterName: kubernetes
            controllerManager: {}
            dns: {}
            etcd:
              local:
                dataDir: /var/lib/etcd
            imageRepository: registry.aliyuncs.com/google_containers
            kind: ClusterConfiguration
            kubernetesVersion: 1.31.0
            networking:
              dnsDomain: cluster.local
              serviceSubnet: 10.96.0.0/16
              podSubnet: 10.244.0.0/16
            scheduler: {}
            ---
            kind: KubeletConfiguration
            apiVersion: kubelet.config.k8s.io/v1beta1
            cgroupDriver: systemd
systemd:
  units:
    - name: kubelet.service
      enabled: true
      dropins:
        - name: 20-kubelet.conf
          contents: |
            [Service]
            ExecStart=
            ExecStart=/opt/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS
    - name: kubeadm.service
      enabled: true
      contents: |
        [Unit]
        Description=Kubeadm service
        Requires=containerd.service
        After=containerd.service
        ConditionPathExists=!/etc/kubernetes/kubelet.conf
        [Service]
        Environment="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/bin"
        ExecStartPre=/opt/bin/kubeadm config images pull
        ExecStartPre=/opt/bin/kubeadm init --config /etc/kubeadm.yml
        ExecStartPre=/usr/bin/mkdir /home/core/.kube
        ExecStartPre=/usr/bin/cp /etc/kubernetes/admin.conf /home/core/.kube/config
        ExecStart=/usr/bin/chown -R core:core /home/core/.kube
        [Install]
        WantedBy=multi-user.target
```

install command:
```
virt-install --connect qemu:///system \
             --import \
             --name flatcar-master-01 \
             --osinfo generic \
             --network bridge=br0,model=virtio \
             --ram 8024 --vcpus 2 \
             --disk path=/var/lib/libvirt/images/flatcar-linux/flatcar-linux1.qcow2,format=qcow2,bus=virtio \
             --vnc --noautoconsole \
             --qemu-commandline="-fw_cfg name=opt/org.flatcar-linux/config,file=/var/lib/libvirt/flatcar-linux/flatcar-linux1/provision170.ign"
```

**Comment by tormath1** [comment]
As discussed on Matrix, `/etc/hosts` needs to be overwritten and console logs can be seen with `console=ttyS0` as Kernel argument parameter.
I'm closing this issue, let's continue to discuss on Matrix. 
```yaml
storage:
  files:
    - path: /etc/hosts
      overwrite: true
      contents:
        inline: |
          192.168.229.170 k8s-master01
          192.168.229.171 k8s-worker01
          192.168.229.172 k8s-worker02
```
