### ISSUE TITLE
[RFE] Update flatcar-container.tar.gz to work with Incus

### ISSUE THREAD

**Issue by tormath1** [kinvolk/Flatcar#1752]
## Current situation

`flatcar-container.tar.gz` can't be used at the moment to run a Flatcar Incus image.

This is more for reference purposes in case someone wants to give a try again. Using [`distrobuilder`](https://github.com/lxc/distrobuilder), one can create an image using this `image.yaml` definition:
```yaml
---
# image.yaml
image:
  distribution: flatcar
  description: Flatcar Beta 4230.1.1
  expiry: 30d
  variant: builder
  architecture: amd64

source:
  downloader: rootfs-http
  url: https://beta.release.flatcar-linux.net/amd64-usr/4230.1.1/flatcar-container.tar.gz

environment:
  clear_defaults: true
  variables:
    - key: "SHELL"
      value: "/usr/bin/bash"

files:
 - path: /etc/hostname
   generator: hostname

 - path: /etc/hosts
   generator: hosts

packages:
  custom_manager:
    clean:
      cmd: true
    install:
      cmd: true
    remove:
      cmd: true
    refresh:
      cmd: true
    update:
      cmd: true
```

Using the `distrobuilder` cli:
```
sudo distrobuilder build-incus image.yaml --compression gzip
```

This will create two files:
* the metadata compressed file
* the rootfs file (squashfs)

Those two files can be used to import a Flatcar image on Incus:
```bash
incus image import incus.tar.gz rootfs.squashfs --alias flatcar-beta-4230.1.1
```

When running the instance:
```bash
core@localhost ~ $ incus launch flatcar-beta-4230.1.1 flatar-01
Launching flatar-01
Error: Failed to run: /usr/bin/incusd forkstart flatar-01 /var/lib/incus/containers /run/incus/flatar-01/lxc.conf: exit status 1
core@localhost ~ $ sudo cat /var/log/incus/flatar-01/lxc.log
lxc flatar-01 20250520145918.583 ERROR    start - ../lxc-6.0.3/src/lxc/start.c:start:2204 - No such file or directory - Failed to exec "/sbin/init"
lxc flatar-01 20250520145918.583 ERROR    sync - ../lxc-6.0.3/src/lxc/sync.c:sync_wait:34 - An error occurred in another process (expected sequence number 7)
lxc flatar-01 20250520145918.586 WARN     network - ../lxc-6.0.3/src/lxc/network.c:lxc_delete_network_priv:3674 - Failed to rename interface with index 0 from "eth0" to its initial name "veth166cd07f"
lxc flatar-01 20250520145918.586 ERROR    lxccontainer - ../lxc-6.0.3/src/lxc/lxccontainer.c:wait_on_daemonized_start:837 - Received container state "ABORTING" instead of "RUNNING"
lxc flatar-01 20250520145918.587 ERROR    start - ../lxc-6.0.3/src/lxc/start.c:__lxc_start:2114 - Failed to spawn container "flatar-01"
lxc flatar-01 20250520145918.587 WARN     start - ../lxc-6.0.3/src/lxc/start.c:lxc_abort:1037 - No such process - Failed to send SIGKILL via pidfd 17 for process 2269
lxc 20250520145918.700 ERROR    af_unix - ../lxc-6.0.3/src/lxc/af_unix.c:lxc_abstract_unix_recv_fds_iov:218 - Connection reset by peer - Failed to receive response
lxc 20250520145918.700 ERROR    commands - ../lxc-6.0.3/src/lxc/commands.c:lxc_cmd_rsp_recv_fds:128 - Failed to receive file descriptors for command "get_init_pid"
```

## Impact

One can't run a Flatcar image with Incus.

## Implementation options

The:
```
lxc flatar-01 20250520145918.583 ERROR    start - ../lxc-6.0.3/src/lxc/start.c:start:2204 - No such file or directory - Failed to exec "/sbin/init"
```

Seems to be the main issue. I tried to update `flatcar-container.tar.gz` to add this symlink:
```
core@localhost ~ $ ls -l /mnt/
total 0
drwxr-xr-x. 2 1000 1000   3 Apr 30 11:46 boot
drwxr-xr-x. 2 root root   3 May 20 14:56 dev
drwxr-xr-x. 2 root root  34 May 20 14:56 etc
drwxr-xr-x. 2 1000 1000   3 Apr 30 11:46 oem
drwxr-xr-x. 2 root root   3 May 20 14:56 proc
drwxr-xr-x. 2 root root   3 May 20 14:56 run
lrwxrwxrwx. 1 1000 1000   8 May 20 14:54 sbin -> usr/bin/
drwxr-xr-x. 2 root root   3 May 20 14:56 sys
drwxr-xr-x. 2 root root   3 May 20 14:56 tmp
drwxr-xr-x. 9 1000 1000 178 Apr 30 11:56 usr
```

but no more luck.
